const postController = require("../controllers/post.controller");
const express = require("express");
const { authJwt } = require("../middlewares");
const router = express.Router();
router.delete("/delete/:postID", postController.delete);
router.patch("/remove/:postID", postController.remove);
router.patch("/update/:postID", postController.update);
router.post("/create", postController.create);
router.get("/getAll", postController.getAll);
router.get("/", postController.index);
router.get("/:postID", postController.getPostID);
module.exports = router;
